 version: '3'

 services:
  apigw:
    image: fileserver/apigw
    ports:
      - "8000:8000"
  upload:
    image: fileserver/upload
    ports:
      - "28000:28000"
    volumes:
      - "/home/zerxoi/fileserver:/fileserver"
  account:
    image: fileserver/account
  transfer:
    image: fileserver/transfer
    volumes:
      - "/home/zerxoi/fileserver:/fileserver"
  dbproxy:
    image: fileserver/dbproxy