// Code generated by protoc-gen-go. DO NOT EDIT.
// source: trans.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReqTrans struct {
	FileSha1             string   `protobuf:"bytes,1,opt,name=fileSha1,proto3" json:"fileSha1,omitempty"`
	CurLocation          string   `protobuf:"bytes,2,opt,name=curLocation,proto3" json:"curLocation,omitempty"`
	DestLocation         string   `protobuf:"bytes,3,opt,name=destLocation,proto3" json:"destLocation,omitempty"`
	DestStoreType        int32    `protobuf:"varint,4,opt,name=destStoreType,proto3" json:"destStoreType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqTrans) Reset()         { *m = ReqTrans{} }
func (m *ReqTrans) String() string { return proto.CompactTextString(m) }
func (*ReqTrans) ProtoMessage()    {}
func (*ReqTrans) Descriptor() ([]byte, []int) {
	return fileDescriptor_afbc80efa276a497, []int{0}
}

func (m *ReqTrans) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqTrans.Unmarshal(m, b)
}
func (m *ReqTrans) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqTrans.Marshal(b, m, deterministic)
}
func (m *ReqTrans) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqTrans.Merge(m, src)
}
func (m *ReqTrans) XXX_Size() int {
	return xxx_messageInfo_ReqTrans.Size(m)
}
func (m *ReqTrans) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqTrans.DiscardUnknown(m)
}

var xxx_messageInfo_ReqTrans proto.InternalMessageInfo

func (m *ReqTrans) GetFileSha1() string {
	if m != nil {
		return m.FileSha1
	}
	return ""
}

func (m *ReqTrans) GetCurLocation() string {
	if m != nil {
		return m.CurLocation
	}
	return ""
}

func (m *ReqTrans) GetDestLocation() string {
	if m != nil {
		return m.DestLocation
	}
	return ""
}

func (m *ReqTrans) GetDestStoreType() int32 {
	if m != nil {
		return m.DestStoreType
	}
	return 0
}

type RespTrans struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespTrans) Reset()         { *m = RespTrans{} }
func (m *RespTrans) String() string { return proto.CompactTextString(m) }
func (*RespTrans) ProtoMessage()    {}
func (*RespTrans) Descriptor() ([]byte, []int) {
	return fileDescriptor_afbc80efa276a497, []int{1}
}

func (m *RespTrans) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespTrans.Unmarshal(m, b)
}
func (m *RespTrans) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespTrans.Marshal(b, m, deterministic)
}
func (m *RespTrans) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespTrans.Merge(m, src)
}
func (m *RespTrans) XXX_Size() int {
	return xxx_messageInfo_RespTrans.Size(m)
}
func (m *RespTrans) XXX_DiscardUnknown() {
	xxx_messageInfo_RespTrans.DiscardUnknown(m)
}

var xxx_messageInfo_RespTrans proto.InternalMessageInfo

func (m *RespTrans) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RespTrans) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*ReqTrans)(nil), "proto.ReqTrans")
	proto.RegisterType((*RespTrans)(nil), "proto.RespTrans")
}

func init() { proto.RegisterFile("trans.proto", fileDescriptor_afbc80efa276a497) }

var fileDescriptor_afbc80efa276a497 = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0xbf, 0x4e, 0x80, 0x30,
	0x18, 0xc4, 0xad, 0x82, 0xc2, 0x87, 0x06, 0xf3, 0x4d, 0x0d, 0x13, 0x69, 0x1c, 0x98, 0x30, 0xea,
	0xe4, 0xea, 0xec, 0x54, 0x78, 0x81, 0x5a, 0x3e, 0x94, 0x44, 0x29, 0xb6, 0xd5, 0xc4, 0xd7, 0xf0,
	0x89, 0x0d, 0xe5, 0x4f, 0x64, 0x6a, 0xef, 0x77, 0xd7, 0xf4, 0x0e, 0x32, 0x6f, 0xd5, 0xe8, 0xea,
	0xc9, 0x1a, 0x6f, 0x30, 0x0e, 0x87, 0xf8, 0x65, 0x90, 0x48, 0xfa, 0x6c, 0x67, 0x07, 0x0b, 0x48,
	0xfa, 0xe1, 0x9d, 0x9a, 0x37, 0x75, 0xc7, 0x59, 0xc9, 0xaa, 0x54, 0xee, 0x1a, 0x4b, 0xc8, 0xf4,
	0x97, 0x7d, 0x36, 0x5a, 0xf9, 0xc1, 0x8c, 0xfc, 0x34, 0xd8, 0xff, 0x11, 0x0a, 0xb8, 0xec, 0xc8,
	0xf9, 0x3d, 0x72, 0x16, 0x22, 0x07, 0x86, 0x37, 0x70, 0x35, 0xeb, 0xc6, 0x1b, 0x4b, 0xed, 0xcf,
	0x44, 0x3c, 0x2a, 0x59, 0x15, 0xcb, 0x23, 0x14, 0x8f, 0x90, 0x4a, 0x72, 0xd3, 0x52, 0x0a, 0x21,
	0xd2, 0xa6, 0xa3, 0x50, 0x28, 0x96, 0xe1, 0x8e, 0x1c, 0x2e, 0x3e, 0xc8, 0x39, 0xf5, 0x4a, 0x6b,
	0x91, 0x4d, 0xde, 0x3f, 0x41, 0x1e, 0x9e, 0xf5, 0x64, 0x1b, 0xb2, 0xdf, 0x83, 0x26, 0xbc, 0x85,
	0x64, 0x43, 0x98, 0x2f, 0xeb, 0xeb, 0x6d, 0x72, 0x71, 0xbd, 0x83, 0xf5, 0x3f, 0x71, 0xf2, 0x72,
	0x1e, 0xd0, 0xc3, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x39, 0xd6, 0xcb, 0xe2, 0x30, 0x01, 0x00,
	0x00,
}
